apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: tempo-1.24.1
    releaseName: tempo
    valuesFile: values.yaml
    namespace: observability